# Generated by Django 2.2.5 on 2019-10-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PbossOrderStatus',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='状态id')),
                ('order_area', models.CharField(max_length=32, verbose_name='区域/省份')),
                ('order_starttime', models.DateTimeField(verbose_name='开始时间')),
                ('order_endtime', models.DateTimeField(verbose_name='结束时间')),
                ('order_cbbsfailed', models.IntegerField(verbose_name='计费反馈同步失败')),
                ('order_startfailed', models.IntegerField(verbose_name='流程启动异常')),
                ('order_cbbssyncing', models.IntegerField(verbose_name='同步计费中')),
                ('order_syncfailed', models.IntegerField(verbose_name='发起同步失败')),
                ('order_cbbssynced', models.IntegerField(verbose_name='已发送计费同步请求')),
                ('order_completed', models.IntegerField(verbose_name='已竣工')),
                ('order_pending', models.IntegerField(verbose_name='待施工处理')),
                ('order_processing', models.IntegerField(verbose_name='施工处理中')),
                ('order_cbbssyncpending', models.IntegerField(verbose_name='待同步计费')),
            ],
            options={
                'verbose_name': 'PBOSS订单状态观察表',
                'verbose_name_plural': 'PBOSS订单状态观察表',
                'db_table': 'order_pboss_status',
                'ordering': ['order_id'],
            },
        ),
    ]
