# Generated by Django 2.2.5 on 2019-10-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CN171_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PbossOrderRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('record_type', models.CharField(max_length=32, verbose_name='类型')),
                ('record_mode', models.CharField(max_length=16, verbose_name='生成方式')),
                ('record_createtime', models.DateTimeField(verbose_name='执行时间')),
                ('record_result', models.CharField(max_length=16, verbose_name='执行结果')),
                ('record_filedir', models.TextField(verbose_name='文件地址')),
            ],
            options={
                'verbose_name': 'PBOSS订单生成记录表',
                'verbose_name_plural': 'PBOSS订单生成记录表',
                'db_table': 'order_pboss_record',
                'ordering': ['-record_id'],
            },
        ),
    ]
