# Generated by Django 2.2.5 on 2019-10-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CN171_order', '0002_pbossorderrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pbossorderrecord',
            options={'ordering': ['-record_createtime'], 'verbose_name': 'PBOSS订单生成记录表', 'verbose_name_plural': 'PBOSS订单生成记录表'},
        ),
    ]
