# Generated by Django 2.2.5 on 2019-09-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BgDomainStatusDict',
            fields=[
                ('bg_domainstatus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bg_domainstatus', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': '中心状态字典表',
                'verbose_name_plural': '中心状态字典表',
                'db_table': 'bg_domainstatus_dict',
            },
        ),
        migrations.CreateModel(
            name='BgTaskLog',
            fields=[
                ('bg_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('bg_id', models.IntegerField()),
                ('bg_operation_user', models.CharField(blank=True, max_length=56, null=True)),
                ('bg_operation', models.CharField(blank=True, max_length=32, null=True)),
                ('bg_opr_result', models.CharField(blank=True, max_length=32, null=True)),
                ('bg_operation_time', models.DateTimeField(auto_now_add=True)),
                ('bg_log_dir', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': '后台管理日志表',
                'verbose_name_plural': '后台管理日志表',
                'db_table': 'bg_task_log',
            },
        ),
        migrations.CreateModel(
            name='BgTaskManagement',
            fields=[
                ('bg_id', models.AutoField(primary_key=True, serialize=False)),
                ('bg_module', models.CharField(max_length=56)),
                ('bg_domain', models.CharField(max_length=56)),
                ('bg_status', models.CharField(blank=True, max_length=32, null=True)),
                ('bg_lastopr_user', models.CharField(blank=True, max_length=56, null=True)),
                ('bg_lastopr_type', models.CharField(blank=True, max_length=32, null=True)),
                ('bg_lastopr_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('bg_lastopr_result', models.CharField(blank=True, max_length=32, null=True)),
                ('bg_task_start', models.TextField()),
                ('bg_task_stop', models.TextField()),
                ('bg_task_restart', models.TextField()),
                ('bg_task_query', models.TextField()),
                ('bg_insert_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '后台管理表',
                'verbose_name_plural': '后台管理表',
                'db_table': 'bg_task_management',
            },
        ),
    ]
