# Generated by Django 2.2.5 on 2019-09-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CN171_background', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgtaskmanagement',
            options={'ordering': ['bg_id'], 'verbose_name': '后台管理表', 'verbose_name_plural': '后台管理表'},
        ),
        migrations.AlterField(
            model_name='bgtasklog',
            name='bg_log_dir',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
