# Generated by Django 2.2.5 on 2019-09-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CN171_background', '0002_auto_20190929_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgtaskmanagement',
            name='bg_domain',
            field=models.CharField(max_length=56, verbose_name='中心'),
        ),
        migrations.AlterField(
            model_name='bgtaskmanagement',
            name='bg_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='后台ID'),
        ),
        migrations.AlterField(
            model_name='bgtaskmanagement',
            name='bg_insert_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='bgtaskmanagement',
            name='bg_lastopr_result',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='最后一次操作结果'),
        ),
        migrations.AlterField(
            model_name='bgtaskmanagement',
            name='bg_lastopr_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后一次操作时间'),
        ),
        migrations.AlterField(
            model_name='bgtaskmanagement',
            name='bg_lastopr_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='最后一次操作类型'),
        ),
        migrations.AlterField(
            model_name='bgtaskmanagement',
            name='bg_lastopr_user',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='最后一次操作人员'),
        ),
        migrations.AlterField(
            model_name='bgtaskmanagement',
            name='bg_module',
            field=models.CharField(max_length=56, verbose_name='模块'),
        ),
        migrations.AlterField(
            model_name='bgtaskmanagement',
            name='bg_status',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='bgtaskmanagement',
            name='bg_task_query',
            field=models.TextField(verbose_name='查询脚本命令'),
        ),
        migrations.AlterField(
            model_name='bgtaskmanagement',
            name='bg_task_restart',
            field=models.TextField(verbose_name='重启脚本命令'),
        ),
        migrations.AlterField(
            model_name='bgtaskmanagement',
            name='bg_task_start',
            field=models.TextField(verbose_name='启动脚本命令'),
        ),
        migrations.AlterField(
            model_name='bgtaskmanagement',
            name='bg_task_stop',
            field=models.TextField(verbose_name='停止脚本命令'),
        ),
    ]
