# Generated by Django 2.2.5 on 2019-12-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CN171_operation', '0002_auto_20191209_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oprfinance',
            name='opr_reco_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后稽核操作时间'),
        ),
        migrations.AlterField(
            model_name='oprfinancefiledetail',
            name='opr_finance_filedetail_lasttime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次更新时间'),
        ),
    ]
