# Generated by Django 2.2.5 on 2019-12-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CN171_operation', '0004_auto_20191219_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oprfinancefiledetail',
            name='opr_finance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', to='CN171_operation.OprFinance'),
        ),
    ]
