# Generated by Django 2.2.5 on 2019-12-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CN171_operation', '0005_auto_20191223_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oprfinancefiledetail',
            name='opr_finance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='CN171_operation.OprFinance'),
        ),
    ]
