# Generated by Django 2.2.5 on 2019-12-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CN171_operation', '0006_auto_20191223_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oprfinancefiledetail',
            name='opr_finance_filedetail_dir',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='文件存储地址'),
        ),
    ]
