# Generated by Django 2.2.5 on 2019-12-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CN171_operation', '0007_auto_20191227_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oprfinance',
            old_name='opr_bc_acc',
            new_name='opr_bc_acct',
        ),
    ]
