# Generated by Django 2.2.5 on 2020-01-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CN171_operation', '0012_oprfinanceuploadrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='oprfinanceuploadrecord',
            name='opr_finance_upload_faillist',
            field=models.TextField(blank=True, null=True, verbose_name='上传失败文件清单'),
        ),
        migrations.AddField(
            model_name='oprfinanceuploadrecord',
            name='opr_finance_upload_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='上传次数'),
        ),
        migrations.AlterField(
            model_name='oprfinanceuploadrecord',
            name='opr_finance_upload_list',
            field=models.TextField(blank=True, null=True, verbose_name='上传文件清单'),
        ),
    ]
