# Generated by Django 2.2.5 on 2019-09-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('acc_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_user_name', models.CharField(max_length=128, unique=True)),
                ('acc_user_CNname', models.CharField(max_length=128, unique=True)),
                ('acc_user_password', models.CharField(max_length=256)),
                ('acc_role_name', models.CharField(blank=True, max_length=30, null=True)),
                ('acc_user_status', models.CharField(blank=True, max_length=30, null=True)),
                ('acc_user_createtime', models.DateTimeField(auto_now_add=True)),
                ('acc_user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('acc_user_mobile', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'acc_user',
            },
        ),
    ]
